# Custom dabble node for handling the middle scalene stretch

# It takes in tracking IDs and keypoints from model.posenet
input: ['img', 'keypoints', 'obj_attrs']

# It outputs the angles and repetitions of the middle scalene stretch
output: ['max_angle', 'min_angle', 'reps']