# Custom dabble node for handling the Y-W stretch

# It takes in tracking IDs and keypoints from model.posenet
input: ['img', 'keypoints', 'obj_attrs']

# It outputs the angles and repetitions of the Y-W stretch
output: ['max_angle', 'min_angle', 'pos', 'reps']