import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Stretch925</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
        <img src="../assets/logo.svg" alt=""/>
        <div className={styles.navButtonsContainer}>
          <button className={styles.navButton}>Why Stretch925?</button>
          <button className={styles.navButton}>How it works</button>
          <button className={`${styles.navButton} ${styles.loginButton}`}>Login</button>
        </div>
      </div>
      <div className={`${styles.main} ${inter.className}`}>
        <div className={styles.banner}>
          <div className={styles.bannerText}>
            <h1>Stretch & Score: <br/> Energize, Strengthen, and Earn Rewards!</h1>
            <button>Try Stretch925 now!</button>
          </div>
          <img src="../assets/banner-image.png" alt=""/>
        </div>
        <div className={styles.whySection}>
          <p>In today's working world, where prolonged sitting has become the norm, incorporating stretching into your routine is essential. It counteracts the negative effects of sitting by improving circulation, reducing muscle stiffness, and preventing aches and pains. Beyond the physical benefits, stretching offers a mental escape, reducing stress and enhancing clarity. Our app empowers you to prioritize your well-being, break free from the sedentary cycle, and experience the remarkable benefits of stretching for a healthier, more balanced lifestyle</p>
        </div>
      </div>
    </>
  )
}
