import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRef } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const whyRef = useRef();
  const howRef = useRef();

  const scrollTo = (section) => {
    if (section === "why") {
      whyRef.current.scrollIntoView();
    } else if (section === "how") {
      howRef.current.scrollIntoView();
    }
  }

  return (
    <>
      <Head>
        <title>Stretch925</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
        <img src="../assets/logo.svg" alt=""/>
        <div className={styles.navButtonsContainer}>
          <button className={styles.navButton} onClick={() => scrollTo("why")}>WhyStretch925?</button>
          <button className={styles.navButton} onClick={() => scrollTo("how")}>How it works</button>
          <button className={`${styles.navButton} ${styles.loginButton}`}>Login</button>
        </div>
      </div>
      <div className={`${styles.main} ${inter.className}`}>
        <div className={styles.banner}>
          <div className={styles.bannerText}>
            <h1>Stretch & Score: <br/> Energize, Strengthen, and Earn Rewards!</h1>
            <Link href="/timer"><button>Try Stretch925 now!</button></Link>
          </div>
          <img src="../assets/banner-image.png" alt=""/>
        </div>
        <div className={styles.whySection} ref={whyRef}>
          <div className={styles.content}>
            <h1>Why  <span style={{color: "#fff"}}>Stretch925?</span></h1>
            <p>In today's working world, where prolonged sitting has become the norm, incorporating stretching into your routine is essential. It counteracts the negative effects of sitting by improving circulation, reducing muscle stiffness, and preventing aches and pains. Beyond the physical benefits, stretching offers a mental escape, reducing stress and enhancing clarity. Our app empowers you to prioritize your well-being, break free from the sedentary cycle, and experience the remarkable benefits of stretching for a healthier, more balanced lifestyle.</p>
          </div>
        </div>
        <div className={styles.HowSectionH1} ref={howRef}>
          <h1>How It Works</h1>
        </div>
        <div className={styles.container}>
          <div className={styles.group}>
            <img className={styles.resizedImage} src="../assets/pomodoro.png" alt="" />
            <div className={styles.itemContent}>
              <h2>Set a Time</h2>
              <p>We know that pomodoros are the in thing these days. <br></br> Feel productive even when resting.</p>
            </div>
          </div>
          <div className={styles.group}>
            <img className={styles.resizedImage} src="../assets/stretch.png" alt="" />
            <div className={styles.itemContent}>
              <h2>Stretch Your Rest</h2>
              <p>Get the most out of your break. It's simple, just 3 stretches <br></br> randomly chosen for you.</p>
            </div>
          </div>
          <div className={styles.group}>
            <img className={styles.resizedImage} src="../assets/webcam.png" alt="" />
            <div className={styles.itemContent}>
              <h2>Follow Along</h2>
              <p>Turn on your webcam and Stretch! The harder the better!</p>
            </div>
          </div>
          <div className={styles.group}>
            <img className={`${styles.resizedImage} ${styles.lastImage}`} src="../assets/trophy.png" alt="" />
            <div className={styles.itemContent}>
              <br></br>
              <br></br>
              <h2>Rankings and Rewards</h2>
              <p>Have fun staying healthy with your colleagues. A little stretch goes a long way!</p>
            </div>
          </div>
        </div>




      </div>
    </>
  )
}

